# Generated by Django 4.2.6 on 2023-11-25 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dragon', '0002_meeting_upload_file_alter_meeting_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='working_setting',
            name='meeting_price',
            field=models.FloatField(),
        ),
    ]
