# Generated by Django 4.2.6 on 2024-01-06 07:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("call_expert", "0046_alter_call_expert_call_type"),
        ("dragon", "0005_upload_file_remove_meeting_upload_file_meeting_files"),
    ]

    operations = [
        migrations.DeleteModel(
            name="upload_file",
        ),
        migrations.AlterField(
            model_name="meeting",
            name="files",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="dragon_meeting_files",
                to="call_expert.upload_file",
            ),
        ),
    ]
