# Generated by Django 4.2.6 on 2023-10-31 20:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0003_favoriteproduct_cartproduct"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="matireal",
            name="product",
        ),
        migrations.AddField(
            model_name="product",
            name="matireal",
            field=models.ManyToManyField(to="product.matireal"),
        ),
    ]
