# Generated by Django 4.2.6 on 2023-10-31 20:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0004_remove_matireal_product_product_matireal"),
    ]

    operations = [
        migrations.RenameField(
            model_name="matireal",
            old_name="persentage",
            new_name="percentage",
        ),
    ]
