# Generated by Django 4.2.6 on 2023-11-08 17:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0005_rename_persentage_matireal_percentage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productdesign",
            name="product",
        ),
        migrations.RemoveField(
            model_name="productdesign",
            name="size",
        ),
    ]
