# Generated by Django 4.2.6 on 2023-11-12 20:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0006_remove_productdesign_product_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productdesign",
            name="frontimage",
            field=models.ImageField(
                blank=True, null=True, upload_to="product/productdesign_image"
            ),
        ),
        migrations.AddField(
            model_name="productdesign",
            name="name",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
