# Generated by Django 4.2.6 on 2023-11-13 20:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0007_productdesign_frontimage_productdesign_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="size",
            name="price",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
