# Generated by Django 4.2.6 on 2023-11-14 20:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0008_size_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="size",
            name="height",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="size",
            name="width",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
