# Generated by Django 4.2.6 on 2023-11-21 01:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0010_remove_size_height_remove_size_price_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="height",
        ),
        migrations.RemoveField(
            model_name="product",
            name="price",
        ),
        migrations.AddField(
            model_name="size",
            name="height",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="size",
            name="price",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="size",
            name="width",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
