# Generated by Django 4.2.6 on 2023-11-28 16:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0012_remove_size_height_remove_size_width_product_height"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartproduct",
            name="back_design_price",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cartproduct",
            name="backcanvas",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cartproduct",
            name="front_design_price",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cartproduct",
            name="frontcanvas",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cartproduct",
            name="quantity",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cartproduct",
            name="quantity_price",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cartproduct",
            name="total_price",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
