# Generated by Django 4.2.6 on 2023-11-28 16:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "product",
            "0013_cartproduct_back_design_price_cartproduct_backcanvas_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartproduct",
            name="back_design_price",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="cartproduct",
            name="front_design_price",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="cartproduct",
            name="quantity_price",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="cartproduct",
            name="total_price",
            field=models.FloatField(),
        ),
    ]
