# Generated by Django 4.2.6 on 2023-11-28 19:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0014_alter_cartproduct_back_design_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartproduct",
            name="product_color",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
