# Generated by Django 4.2.6 on 2023-11-30 04:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("product", "0015_cartproduct_product_color"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productdesign",
            name="user",
        ),
        migrations.AddField(
            model_name="productdesign",
            name="user",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
