# Generated by Django 4.2.6 on 2023-11-30 04:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0016_remove_productdesign_user_productdesign_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartproduct",
            name="back_design",
            field=models.ImageField(
                blank=True, null=True, upload_to="product/cartproduct_image"
            ),
        ),
        migrations.AddField(
            model_name="cartproduct",
            name="front_design",
            field=models.ImageField(
                blank=True, null=True, upload_to="product/cartproduct_image"
            ),
        ),
    ]
