# Generated by Django 4.2.6 on 2023-12-02 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_remove_cartproduct_back_design_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
    ]
