# Generated by Django 4.2.6 on 2023-12-02 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0019_alter_product_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="CardSize",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=50)),
                ("quantity", models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name="cartproduct",
            name="sizes",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="product.cardsize",
            ),
            preserve_default=False,
        ),
    ]
