# Generated by Django 4.2.6 on 2023-12-02 13:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0020_cardsize_cartproduct_sizes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartproduct",
            name="sizes",
        ),
        migrations.AddField(
            model_name="cartproduct",
            name="sizes",
            field=models.ManyToManyField(to="product.cardsize"),
        ),
    ]
