# Generated by Django 4.2.6 on 2023-12-05 16:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0023_order_methods_of_receiving"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="methods_of_receiving",
            field=models.CharField(default="pickup", max_length=50),
        ),
    ]
