# Generated by Django 4.2.6 on 2023-12-27 13:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0025_cartproduct_back_tshirt_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
