# Generated by Django 4.2.6 on 2024-01-01 20:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0026_product_is_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="DesignImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="product/designimage_image")),
            ],
        ),
        migrations.AddField(
            model_name="cartproduct",
            name="design_images",
            field=models.ManyToManyField(to="product.designimage"),
        ),
    ]
