# Generated by Django 4.2.6 on 2024-01-01 20:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0027_designimage_cartproduct_design_images"),
    ]

    operations = [
        migrations.AlterField(
            model_name="designimage",
            name="image",
            field=models.TextField(),
        ),
    ]
