# Generated by Django 4.2.6 on 2024-01-03 00:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0028_alter_designimage_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="order_receiving_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
