# Generated by Django 4.2.6 on 2024-01-04 17:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0029_order_order_receiving_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="designimage",
            name="image",
        ),
        migrations.AddField(
            model_name="designimage",
            name="file",
            field=models.ImageField(default=1, upload_to="design_images/"),
            preserve_default=False,
        ),
    ]
