# Generated by Django 4.2.6 on 2024-01-04 17:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0030_remove_designimage_image_designimage_file"),
    ]

    operations = [
        migrations.RenameField(
            model_name="designimage",
            old_name="file",
            new_name="image",
        ),
    ]
