# Generated by Django 4.2.6 on 2024-01-04 17:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0031_rename_file_designimage_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="designimage",
            name="image",
            field=models.TextField(),
        ),
    ]
