# Generated by Django 4.2.6 on 2024-01-05 00:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0032_alter_designimage_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(default="pending", max_length=50),
        ),
    ]
