# Generated by Django 4.2.6 on 2024-01-05 01:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0033_order_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("Processing", "Processing"),
                    ("in_Progress", "in_Progress"),
                    ("Ready_For_Pickup", "Ready_For_Pickup"),
                    ("Shipping", "Shipping"),
                    ("Delivered", "Delivered"),
                    ("Finished", "Finished"),
                ],
                default="Processing",
                max_length=50,
            ),
        ),
    ]
