# Generated by Django 4.2.6 on 2024-01-06 22:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0034_alter_order_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartproduct",
            name="design_images",
            field=models.ManyToManyField(
                blank=True, null=True, to="product.designimage"
            ),
        ),
    ]
