# Generated by Django 4.2.6 on 2023-12-05 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0024_alter_order_methods_of_receiving"),
        ("pricing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="productdiscountquantity",
            name="product",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="product.product",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="copoun",
            name="discount",
            field=models.IntegerField(verbose_name="Discount %"),
        ),
        migrations.AlterField(
            model_name="generaldiscount",
            name="discount",
            field=models.IntegerField(verbose_name="Discount %"),
        ),
        migrations.AlterField(
            model_name="printingdiscountquantity",
            name="discount",
            field=models.IntegerField(verbose_name="Discount %"),
        ),
        migrations.AlterField(
            model_name="productdiscountquantity",
            name="discount",
            field=models.IntegerField(verbose_name="Discount %"),
        ),
    ]
