# Generated by Django 4.2.6 on 2023-12-05 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0024_alter_order_methods_of_receiving"),
        ("pricing", "0002_productdiscountquantity_product_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productdiscountquantity",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="product.product",
            ),
        ),
    ]
