# Generated by Django 4.2.6 on 2023-12-05 16:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pricing", "0003_alter_productdiscountquantity_product"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productdiscountquantity",
            name="product",
        ),
    ]
