# Generated by Django 4.2.6 on 2023-12-09 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0025_cartproduct_back_tshirt_image_and_more"),
        ("pricing", "0005_productdiscountquantity_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productdiscountquantity",
            name="product",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="product.product",
            ),
            preserve_default=False,
        ),
    ]
