# Generated by Django 4.2.6 on 2023-12-27 21:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("senior_dragon", "0002_meeting_upload_file"),
    ]

    operations = [
        migrations.DeleteModel(
            name="working_setting",
        ),
    ]
