# Generated by Django 4.2.6 on 2024-01-02 18:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("senior_unicorn", "0002_meeting_upload_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="meeting",
            name="meeting_url",
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
