# Generated by Django 4.2.6 on 2023-11-07 13:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_remove_profile_city_alter_profile_country_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="postal_code",
        ),
    ]
