# Generated by Django 4.2.6 on 2023-11-08 16:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contact_us", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactus",
            name="subject",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
