# Generated by Django 4.2.6 on 2023-12-30 21:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contact_us", "0002_contactus_subject"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactus",
            name="is_read",
            field=models.BooleanField(default=False),
        ),
    ]
