# Generated by Django 4.2.6 on 2023-10-31 20:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("call_expert", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="call_expert",
            name="call_type",
            field=models.CharField(
                choices=[("normal", "normal"), ("professional", "professional")],
                default="normal",
                max_length=20,
            ),
        ),
    ]
