# Generated by Django 4.2.6 on 2024-01-06 22:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("call_expert", "0045_alter_call_expert_call_type"),
        ("call_expert", "0047_alter_call_expert_call_type"),
    ]

    operations = []
